### ISSUE TITLE
Feature: adaptive playback of network streams

### ISSUE THREAD

**Issue by adacaccia** [linuxmint/hypnotix#10]
To avoid the Classic spinner and an annoying buffering %, please do:
- two different threads and a ring buffer: One thread downloads into the ring, the other plays from It.
- ring filling should be monitored by a third thread, which can act on the other two via runtime config, slowing down the download when the player Is back, and/or lowerinng the playback bitrate when the download Is late.

**Comment by clefebvre** [comment]
This is handled by libmpv at the moment.
