### ISSUE TITLE
Channel Buttons

### ISSUE THREAD

**Issue by elhijodelpeje** [linuxmint/hypnotix#100]
When channel Buttons are selected, they should be highlighted, so users can see what are they looking at, or shown in the title bar on top of the screen.

**Comment by Axel-Erfurt** [comment]
I did that in my [fork](https://github.com/Axel-Erfurt/hypnotix), also fixed the error that the providers cannot be deleted or edited.
you can test it by using this hypnotix.py

https://raw.githubusercontent.com/Axel-Erfurt/hypnotix/master/usr/lib/hypnotix/hypnotix.py

if it works you can rename your old hypnotix.py and copy the new to /usr/lib/hypnotix/
