### ISSUE TITLE
Names of TV Stations not displayed correctly

### ISSUE THREAD

**Issue by retrue** [linuxmint/hypnotix#101]
When a TV channel has a name that includes not English characters, that name is not displayed correctly.
For example, accented vowels, Spanish characters like Ñ, Turkish characters like Ö, etc.

**Comment by Free-IPTV** [comment]
> 
> 
> When a TV channel has a name that includes not English characters, that name is not displayed correctly.
> For example, accented vowels, Spanish characters like Ñ, Turkish characters like Ö, etc.

Hi Retrue,

we has make some updates. All files now are saved in UTF-8. Ther should be no problems with characters. :-)
