### ISSUE TITLE
How about to mark some chanals to favorite list? (Feature Request)

### ISSUE THREAD

**Issue by IT-Tool** [linuxmint/hypnotix#102]
Channel lists can be very long so I would like to add some to favorite list or to see the marked channels first in the list.

**Comment by Axel-Erfurt** [comment]
You can create m3u from your favourite channels and import it then.

**Comment by DJCrashdummy** [comment]
this is a duplicate of #36.

**Comment by Abu-Daud** [comment]
I agree that this is a needed feature.  As a start, what about a way to pull the url of the currently playing stream to the clipboard or show it in a log file?

**Comment by clefebvre** [comment]
This will happen. Closing the issue.

**Comment by IT-Tool** [comment]
duplicate of #126
