### ISSUE TITLE
Free-IPTV is down

### ISSUE THREAD

**Issue by Free-IPTV** [linuxmint/hypnotix#107]
Hi,

einfach in deutsch, habe auf englisch jetzt keinen Bock. Eine wichtige Info für euch. Momentan nutzt ihr (noch) meine M3U´s. Mein Repo:

wird jetzt erst einmal aus mehreren Gründen (Hetzkampagen gegen mich, Verleundung, Lügen), nicht nur damls im Forum NZ / (AU sonder mittlerweile auch im Forum in Deutschland! Es reicht, ich investierte viel Freizeit in mein Projekt, was ist der Dank dafür? Nur Neid, Missgunst und etc.

Im Gegensatz zu eucht (ich bekam damals keine Infos, dass ihr meine M3U´s nutzen wollt) informiere ich euch vorher!

Das Repo wird auf Privat umgestellt, zu gegebener Zeit stelle ich es vielleicht wieder auf Öffentlich um, wenn sich die Lage beruhigt hat!

**Comment by clefebvre** [comment]
Hi,

Sorry I can't reply in German, I don't speak this language. What is the issue you're getting exactly? Did it make your project grow too fast in terms of number of users? Sorry, I don't really understand the problem itself.

In any case if you don't want people to use your project, we'll gladly stop using it. There's no problem with that. Maybe put it in your README you don't want people to do so.. or keep it private if it's not meant to be used.

**Comment by NikoKrause** [comment]
Hallo @Free-IPTV,

tut mir leid zu hören, dass du da nur negative Kommentare erhalten hast. Auf welche Foren beziehst du dich. Ich bin da nicht so viel in Foren unterwegs, sollten das Linux Mint Foren sein, dann könnte ich da die Mint Forum-Admins informieren, dass sie sich das ansehen. Kannst mir die Links auch gerne per Mail zuschicken, wenn dir das lieber ist.

Das du nicht informiert wurdest, das dein Projekt in Hypnotix verwendet wurde, war definitiv keine böse Absicht. Normalerweise informiert Clem die Creator, wenn Projekte von denen genutzt werden, z.B. Timeshift oder Moka Icons fallen mir da ein. Solltest du dich übergangen gefühlt haben, kann man das bestimmt klären. Kannst auch gerne ne Mail schreiben, um deine Sichtweise zu erläutern, da ich ehrlich gesagt auch nicht weiß, was du alles für Hate etc. erfahren hast. Wir machen Clem mal auf deine Situation aufmerksam. Bin mir sicher, dass er sich früher oder später bei dir oder hier auch zu Wort meldet. 

Vielen Dank für die Info und hoffentlich beruhigt sich die Lage Recht bald.

Viele Grüße
Niko

**Comment by clefebvre** [comment]
Thanks Niko.

The content has a huge number of forks. I found 2 and added another which are pretty up to date. They don't look like real forks though, just copies/ongoing-rebases.

https://github.com/musuruan/Countries
https://github.com/joseanderson1995silva/Countries
https://github.com/clefebvre/Countries

If Free-IPTV doesn't want to maintain this project (publicly I mean) we'll need to either find someone who does, do it ourselves or ship with no content by default.

**Comment by clefebvre** [comment]
There seems to be some info in the commit msgs.

Hypnotix usage was well received and acknowledged 17 days ago: https://github.com/clefebvre/Countries/commit/5d64ce0b700f43659f03539bd43b444d752feaaa.

Info on controversy here: https://github.com/clefebvre/Countries/commit/b1f4d9ce25ebd95fff49cfd76b6fb9a57c837c08

I'm not sure which forum is the one mentioned in the commit msg though.

**Comment by clefebvre** [comment]
More info:

https://github.com/clefebvre/Countries/commit/2203d710373593620132e61325c12e08b7d99789
https://github.com/clefebvre/Countries/commit/dd4fa3a8fadf05171821344a1470d5c4c8184650
https://github.com/clefebvre/Countries/commit/d0b0981e4d1e4f85b5d38eeafc9e7c5aff5a6178

**Comment by Free-IPTV** [comment]
Hi  NikoKrause ,

nein es war nicht euer Forum. War eins für die Kodinerds! Lese ja die anderen Kommentare hier, Haha... klar, nehmt gerne eines der Forks, wird aber kein Ersatz für mein Repo sein... langfristig! Ich hatte viele Helfer bei Github, sind alle informiert. Zu gegebener Zeit werde ich vielleicht mein Repo wieder auf Öffentlich stellen aber in letzter Zeit war es einfach zu viel. Neid, Missgunst, Trolle aus dem Forum in NZ / AU, die dann auch in das deutsche Forum rüber schwenkten.

Weisst du, ich bin 60 Jahre alt, der Stress wurde mir zu viel. Wenn sich die Lage beruhigt hat, ist mein Repo vielleicht wieder frei verfügbar. Pflegen werde ich es weiterhin, mit seinen mittl. knapp über 3500 freien und legalen Streams. Es gibt so viel illegalen Mist hier bei Github... ich hatte den seriösen Weg gewählt.

**Comment by clefebvre** [comment]
It looks like the issue is about the legality of some of the content.

The intention of the provider to only host legal content is clear. Three things could be added to help with these kind of situations:

- Require proof for PRs which add new streams.
- Merge using squash-and-merge to quickly find PRs from commit msg and thus go straight from a git blame to a PR proof.
- Make it clear in the README that only PRs which can prove the content is legally/widely available will be merged.
- Make it clear in the README that any content can be removed by PR also if proof is given that the content is not legal.

That should delegate the responsibility to the PRs, make it easy to find references and make the mission of the project crystal clear. If anybody has an issue then, they're welcome to create a PR.

**Comment by clefebvre** [comment]
I'd also suggest a donation link @Free-IPTV. I've no doubt this requires a lot of work. It's easy to find illegal IPTV streams, it's much more difficult to find one where people take the time to check things and make sure they're OK. We donate to projects which make ours better, this one is no different.

Anyway, it looks like things need to calm down right now. Let's wait until next week and see where we're at.

**Comment by Free-IPTV** [comment]
Hi clefebvre,

Just give me a few days, I had written to NikoKrause in German why I switched the repo to private. I'll be in touch on Monday and we'll see how things go from here, okay? Sorry, my english is not good.

**Comment by clefebvre** [comment]
No problem. I'll rephrase the issue in the meantime for users wondering why the link is down.

**Comment by CHJ85** [comment]
@Free-IPTV Don't worry about it. Take your time.
And for those that are interested, I'll be keeping my fork of the project up to date.

**Comment by Free-IPTV** [comment]
Hi CHJ85, 

Thanks for your great help, you helped me the most in my repo. I'm having a break...

**Comment by vieirapedros** [comment]
Mann, ich bin wirklich traurig.  Ich benutze Ihre Liste täglich und der Inhalt gefällt mir sehr gut.  Es ist eine Schande, dass ich mir nicht die Zeit nehmen konnte, ein Backup zu erstellen, um den Inhalt zu genießen, während Sie Ihre wohlverdiente Ruhepause bekommen.  Ich hoffe, Google Translate hat gut funktioniert, um meine Wörter zu übersetzen.  eine große Umarmung aus Brasilien!

**Comment by Free-IPTV** [comment]
Obrigado Vieirapedros!

Espero que o Google também traduza isso corretamente. Não tem sido fácil ultimamente, muita inveja, ressentimento e correria de pessoas que simplesmente não gostam do meu repo! Vou apenas fazer uma pequena pausa, perdoe o fracasso. Posso carregar meu M3U (Playlist_ALL) aqui para você? Vou tentar Fique saudável!

[ZZ_PLAYLIST_ALL_TV.zip](https://github.com/linuxmint/hypnotix/files/6045417/ZZ_PLAYLIST_ALL_TV.zip)

**Comment by vieirapedros** [comment]
Du bist unglaublich.  Lass dich nicht von Menschen mit schlechten Herzen verärgern.  Die Guten werden gewinnen!  wir sind zusammen!

**Comment by Free-IPTV** [comment]
Hi @vieirapedros,
thank you!!! :-)

**Comment by Free-IPTV** [comment]
> 
> 
> No problem. I'll rephrase the issue in the meantime for users wondering why the link is down.

Hi @ clefebvre,

they always say you should sleep over it for a night. I have now done that. With my repo I have achieved more than I ever expected. Special thanks is going to CHJ85 he is really great help, it has continued to grow. Few idiots who are simply too stupid to recognize the value of the legal M3U's. Lots of fans who think it's great and also gave great feedback.

What can the many fans do for the behavior of stupid minorities? Nothing, they would be the ones to suffer. So today I open my repo again and I continue as usual. I will keep my distance from the German Kodi form, I don't need it!

Happy weekend for all! 

P.S. A small fundraiser would of course also be great. I am also a victim of Corona and I lost my job at the age of 60.

**Comment by clefebvre** [comment]
Thanks @Free-IPTV,

I understand what you must have been going through. It's not always easy to deal with a massive amount of feedback and scrutiny. Some people really try to bring you down and lack basic etiquette and courtesy. It's not always easy to ignore them and it does have an impact on your moral and the fun you need to keep going. Thankfully there also are people whose criticism is constructive and helpful and many people also whose support help you carry on.

I'm glad you made this decision. I hope you implement the recommendations I made regarding the readme and the PR merging or that you'll find even better solutions to protect your project from this kind of criticism and to make it easy to handle.

We're sending funds your way. Thank you for this project and keep up the great work.

**Comment by Free-IPTV** [comment]
Hi @clefebvre,

i thank you so much! Happy day!!!

**Comment by Free-IPTV** [comment]
Hi @vieirapedros,

thank you!!! You are great. I do my best in future for the project Frr-IPTV.

Happy weekend! :-)
