### ISSUE TITLE
[Feature request] Add option to show more technical information about the stream (e.g. codec, resolution, bitrate, etc.)

### ISSUE THREAD

**Issue by mendel5** [linuxmint/hypnotix#111]
It would be great if `hypnotix` had a button to open a sidebar where technical information about the stream is shown.
For example the Linux Mint program `xplayer` ( https://github.com/linuxmint/xplayer ) has such a sidebar which is called `Properties`.

The technical information about the stream displayed in hypnotix' sidebar could be things such as:
- Video codec
- Video resolution / dimensions
- Video frame rate
- Video bitrate
- Audio codec
- Audio channels (e.g. Stereo)
- Audio sample rate
- Audio bitrate

Here is a screenshot of said sidebar in xplayer:
![screenshot_xplayer_sidebar](https://user-images.githubusercontent.com/60322520/110225162-eaaf5580-7ee2-11eb-9b23-3315ad54972b.png)

**Comment by hcombination** [comment]
#138

**Comment by mendel5** [comment]
Thank you, @hcombination ! Now it only needs to be merged...

**Comment by mendel5** [comment]
https://github.com/linuxmint/hypnotix/pull/138 has been merged. See also clefebvre's comment over there.
