### ISSUE TITLE
Marking of the selected station

### ISSUE THREAD

**Issue by heiler** [linuxmint/hypnotix#113]
I use Hypnotix with Linux Mint 20.1 and Cinnamon.
You can not see which channel is selected. The name is not displayed in the title bar, the marker in the navigation remains with the first selected channel. Please see encl. Screenshot, the selected station is WDR Köln.
Kind regards

![Bildschirmfoto vom 2021-03-07 11-01-34](https://user-images.githubusercontent.com/2920260/110236200-c9775500-7f34-11eb-9b55-629dc2825ef0.png)

**Comment by clefebvre** [comment]
Indeed, we'll get this done.
