### ISSUE TITLE
sudo apt install hypnotix

### ISSUE THREAD

**Issue by Mennaruuk** [linuxmint/hypnotix#114]
Hi! Will there ever be a command to install Hypnotix via apt? Thanks :)

**Comment by JosephMcc** [comment]
Well that depends on someone packaging it for your distro of choice. It's already available in the Mint repos to install this way.

**Comment by Mennaruuk** [comment]
Do you know if there's a way to add this particular repo to Ubuntu? Or is that not the best thing to do?
