### ISSUE TITLE
Could you add url support with "User-Agent" and "Referer" ?

### ISSUE THREAD

**Issue by kodi-rc** [linuxmint/hypnotix#12]
Hi, could you add url support with "User-Agent" and "Referer", as in Kodi?

an example of a minimal add-on for kodi that plays a video with a url that requires "User-Agent" and "Referer"
http://www.mediafire.com/file/90mj1g38sgxg6sk/plugin.video.test-referer.zip/file

url that opens in Kodi:
https://geralorigin.eu-central-1.edge.mycdn.live/live/cultura/video.m3u8|Referer=https://topcanais.com/assistir-tv-cultura-ao-vivo-24-horas-online/&User-Agent=Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

my m3u list-test:
gsettings set org.x.hypnotix providers "['Provider_Name:::https://raw.githubusercontent.com/kodi-rc/redecanais/master/teste.m3u']"

**Comment by clefebvre** [comment]
Yes I think we can do that.

**Comment by clefebvre** [comment]
Done by https://github.com/linuxmint/hypnotix/commit/87a8e61879e92203f655d838ebd38274832b4ebf
