### ISSUE TITLE
Only 1 channel per country

### ISSUE THREAD

**Issue by max1287876** [linuxmint/hypnotix#128]
Hi , during the past days I've got only 1 channel per country .
Why is that ?
And every channels' title is "Say thank you to IPTV ORG!" .

**Comment by Axel-Erfurt** [comment]
https://github.com/linuxmint/hypnotix/issues/124

**Comment by Zhoro-111** [comment]
> Hi , during the past days I've got only 1 channel per country .
> Why is that ?
> And every channels' title is "Say thank you to IPTV ORG!" .

That started 2 days ago,when the old repo been changed to private because iptv-org was stealing the hard work with the biggest insolence!

**Comment by clefebvre** [comment]
This is an issue with the provider, not the hypnotix player so I'm closing it.
