### ISSUE TITLE
Only a few TV stations from 6-7 countries after updating Hypnotix to version 1.6.

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/hypnotix#135]
For Clem!
What I will write bellow is my opinion, as well as a high issue.

From my point of view, I would break up with the so-called "Free-IPTV" because:

- putting only a few TV stations from only about 6-7 countries, "at free", from the person "Free-IPTV" (I think that at your insistence, Clem, in private, he put only a few TV stations in list, he no longer wanted to offer a "free" list), the world will not bother to use Hypnotix and you and the Linux Mint team have struggled in vain to create this superb program;
- this "Free-IPTV" person, who hides in anonymity (meaning that he is not an honest person and may not have picked up all the TV stations legally), is constantly grumpy and has the impression that Linux programs and systems , which are open source, cost; it is normal that in the Open Source world the ideas and the work are "stolen", because this is exactly the idea for the world to help each other.

At the age of the person "No Name", also called "Free-IPTV", who is 61 years old, it should have been more modest, rational and smarter, but it is a great disappointment. This person, at him age, unfortunately does not know what it means to be free. He lives in him own closed world.

What would it be like to be upset that the world "stole" my projects, made in Linux and other programs, as long as I, with my hand, offered them voluntarily for free in virtual public space?

Let's all get upset, offer us absolutely nothing for free, live only for money, without principles and respect.

**I chose to write here, on Github, and not in private, to let Hypnotix users know why they no longer have their favorite TV stations in the program list and only a few or none of their home country.**

For the so-called "Free-IPTV": **thank you "Free-IPTV" for nothing**.

**Comment by PieterHartzer** [comment]
Personal attacks has no place here, it's childish and nobody cares about your personal feelings.  

Many countries (for example the UK) require a TV license for you to watch these channels.  There are also other laws governing which programs are allowed to be showed in which countries and could land you in jail for assisting in the distribution of these content.  They pushed for a 12 year sentence in the UK.

You can create a list of channels in the app and therefore set up whatever you like.  If you don't like it, fork the repo and create your own.

**Comment by Bixbyte01** [comment]
**How I added 7,000 channels to Hypnotix:**
 
Click Providers> Add New Provider>Name:OTHER>URL: **https://iptv-org.github.io/iptv/categories/other.m3u**
>OK
Now select "OTHER" as your new M3U list and you should have 7,000 channels working on Hypnotix 
Tested and ran on 4/17/2021 
Not certain how long this new list will function

**Comment by mtwebster** [comment]
The provider has been changed, which was the reason for the 1.6 update:
https://github.com/linuxmint/hypnotix/commit/a0f5d3b1e2ee99cb562d91182287d56e10a11dbe

Please see the readme:
https://github.com/Free-TV/IPTV
Pull requests to add channels that follow the guidelines are welcome.
