### ISSUE TITLE
Congratulations to your new provider!

### ISSUE THREAD

**Issue by Raspifan2020** [linuxmint/hypnotix#139]
Congratulations on your new provider and already you have illegal streams in Hypnotix for all users!

All streams with the IP 51.52.156.22 are NOT from ITV, but from a third party who has no rights to send the streams.

https://github.com/Free-TV/IPTV/commit/4cefc05de564299c62e14193a91e86448279fcbf

You should have stayed with the previous provider, who followed the rules (DMCA). ;-)

**Comment by clefebvre** [comment]
This should go upstream.
