### ISSUE TITLE
Feature request: Cast to TV like android app Web Video Cast

### ISSUE THREAD

**Issue by kodi-rc** [linuxmint/hypnotix#14]
Feature request:
Please add the option to send the video to the TV, via DLNA even if you don't have a similar chromecast dongle.

just like this android app does Web Video Cast:

https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo&hl=pt_BR

**Comment by clefebvre** [comment]
I'm not against the idea but I'll need implementation details or a pull request for this.
