### ISSUE TITLE
Uk tv channels

### ISSUE THREAD

**Issue by TheMero-maker** [linuxmint/hypnotix#141]
loving how the app works so far , and i know its not your fault but just an observation on channels . itv  work fine, but most of channel 4 and bbc streams fail to play . I know its not Geo location related as i'm in the uk . tested a few of the urls in different players and getting access forbidden , so possibly broken / outdated addresses or format . 
So if anyone else is experiencing the same for their home country channels its looking like its down to the M3U provider and not Hypnotix itself .

**Comment by clefebvre** [comment]
It's upstream with the provider indeed.
