### ISSUE TITLE
I Can't close the mpv player

### ISSUE THREAD

**Issue by oneiroi-el** [linuxmint/hypnotix#142]
When I click on a chanel that open a new window.
But I can't close this window and if I want to switch to an other chanel that open a sedond window that I can't close too.
I don't know if it's because of mpv.
Thanks for having read me.

mpv version : 0.33.1

**Comment by TheMero-maker** [comment]
what version of linux are you using ?

**Comment by oneiroi-el** [comment]
Ok, thank you anyway, I'll try IPTVnator.

**Comment by Axel-Erfurt** [comment]
In Fedora 34, embedding mpv doesn't work with python Gtk or PyQt5, maybe because it uses Wayland.

**Comment by Axel-Erfurt** [comment]
The problem is GdkWaylandWindow has no property get_xid, hypnotix cannot embed and control the external mpv window on wayland.

The only way to use python-mpv on wayland is to use OpenGL

**Comment by Axel-Erfurt** [comment]
Only if you rewrite hypnotix.py

**Comment by oneiroi-el** [comment]
Ok but I don't think I can do it by myself.
Can you help me please ?

**Comment by TheMero-maker** [comment]
Thanks axel I'll try astroncia too, and your m3u editor is fantastic  😊

**Comment by Axel-Erfurt** [comment]
I did a test with Fedora 34.
If you do it as described in ReadMe, it works.

> If you're using Wayland go the Hypnotix preferences and add the following to the list of MPV options:
> vo=x11

> Run Hypnotix with:
> VGDK_BACKEND=x11 hypnotix
