### ISSUE TITLE
Could not find widget info_window_close_button! (on hypnotix 1.7)

### ISSUE THREAD

**Issue by alemswaj** [linuxmint/hypnotix#147]
Hi,
When I want to start the new version of hypnotix (1.7) I got this error :
Could not find widget info_window_close_button!

**Comment by Axel-Erfurt** [comment]
Did you create a deb file?

```
mint-build -g https://github.com/linuxmint/hypnotix.git
```

**Comment by alemswaj** [comment]
I'm on linuxmint. But I figured out, the problem was that I tried to execute the program from downloaded location without update all files of the application.
thanks
