### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by hugok79** [linuxmint/hypnotix#149]
Although the Portuguese(pt) translation has been completed since the first version of Hipnotix, the words "TV Channels", "Movies" and "Series" in the main window still appear in English!
![Captura de ecrã de 2021-06-16 10-30-54](https://user-images.githubusercontent.com/16929048/122198122-c7585700-ce90-11eb-80a9-4ace3b6830f4.png)

**Comment by Axel-Erfurt** [comment]
I don't think these terms are translated in any language. Everyone knows what is meant.

**Comment by hugok79** [comment]
That is not true, the translation exists.
https://translations.launchpad.net/linuxmint/latest/+pots/hypnotix/pt/+translate?memo=10&start=10

**Comment by Axel-Erfurt** [comment]
You understood it wrong. These 3 terms were not translated in the app.
In the German version they are also in English.

**Comment by Carmina16** [comment]
No surprise, those are not marked for translation:
https://github.com/linuxmint/hypnotix/blob/1af9403e0b493fdb87cda7eab06c9c41ccf288e0/usr/lib/hypnotix/hypnotix.py#L530

**Comment by hugok79** [comment]
@Carmina16 Thank you 👍 
 I don't know about code, but now I understand that it has to do with the code and not with the translation itself.

**Comment by hugok79** [comment]
Should we consider this an issue or should it be fixed so that the translation appears in the respective language?

**Comment by Carmina16** [comment]
Yes, the author has to mark them for translation and regenerate the pot file.

**Comment by hugok79** [comment]
Any progress so far?

**Comment by Carmina16** [comment]
@clefebvre it should be trivial to fix I think?

**Comment by hugok79** [comment]
Thank you!
