### ISSUE TITLE
No Indian Channel

### ISSUE THREAD

**Issue by Kakapoudel7** [linuxmint/hypnotix#153]
I don't find any Indian TV Channel, why ? Is there legal issue or what ?

**Comment by Raspifan2020** [comment]
> 
> 
> I don't find any Indian TV Channel, why ? Is there legal issue or what ?

Hi @Kakapoudel7,

here is a list for India, it works fine also in Hypnotix: https://github.com/Free-IPTV/Countries/blob/master/IN01_INDIA.m3u
