### ISSUE TITLE
Tengo una Smartv sistema operativo Linux JVC  pero cienro intalar  aplicasiones por la misma (tv)  inopuedos

### ISSUE THREAD

**Issue by Jesilh** [linuxmint/hypnotix#155]

**Comment by Jesilh** [comment]
![20210728_121611.jpg](https://user-images.githubusercontent.com/88261765/127760326-940a6076-25bb-4c46-91b8-2406acb0490a.jpg)

**Comment by Axel-Erfurt** [comment]
What's the question?

**Comment by evil-arri** [comment]
Dude. You can't install Hypnotix on your TV.

**Comment by Jesilh** [comment]
5.0(LinuxAppleWebKit/537.36 (KHTML, like Gecko)    ehtoro Browser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36

**Comment by Jesilh** [comment]
jvc lt 43kb385 firmware sistema operativo  Linux

**Comment by Jesilh** [comment]
Cómo puedo actualizar jvc lt 43kb385 firmware
