### ISSUE TITLE
Feature Request: Quality Control

### ISSUE THREAD

**Issue by prabhanjan6174** [linuxmint/hypnotix#16]
In developing countries like India, internet coverage is not great in many areas. Playing videos in HD, is highly impossible, it would be nice to have a quality control, for better experience.

**Comment by clefebvre** [comment]
How would it work from a technical point of view? I think it's up to the source to define bitrate and quality.. I'm not sure the client can do anything about it. If I'm wrong please provide more details though in a new issue.
