### ISSUE TITLE
Python module unidecode missing

### ISSUE THREAD

**Issue by brccabral** [linuxmint/hypnotix#169]
Hi everyone,
I just did a build from source, installed the .deb package, but when running it for the first time it threw this error.
`hypnotix.py crashed with ModuleNotFoundError in __main__: No module named 'unidecode'`
By just doing `pip install unidecode` solves the issue and the application runs fine, but is there any way to avoid the problem in a clean environment like I had?

**Comment by cloudykira** [comment]
This is bug in packaging.
See my pull request #166 

Meanwhile you can do ```git checkout 2.0``` if you want to build stable version.

**Comment by cloudykira** [comment]
Also ```sudo apt install python3-unidecode``` is better than pip

**Comment by brccabral** [comment]
Great, easy fix then...
