### ISSUE TITLE
group-title="SERIES" problem on hypnotix

### ISSUE THREAD

**Issue by dasaferi** [linuxmint/hypnotix#170]
Hi, i have see `group-title="SERIES"` attribute does not work in hypnotix, entries with this "tag" are not read in hypnotix do not appear in the Series block, if you try `group-title="VOD"` go in the Movies group, I think there is some problem with the `group-title="SERIES"` attribute. Can you verify and in case fix the problem?

**Comment by Axel-Erfurt** [comment]
Read my explanation about series

https://github.com/Axel-Erfurt/hypnotix#howto-make-playlists-for-series

**Comment by dasaferi** [comment]
> I've tried that and works, but be advised that this is just a quick hack and not a proper solution. Also I didn't check what collateral effects could this have in hypnotix behaviour.

thanks for the moment it seems to work perfectly, from what I understand it works until you not update hypnotix because it is a change not officially implemented.
