### ISSUE TITLE
Bad filtering of XTream live streams

### ISSUE THREAD

**Issue by gromez** [linuxmint/hypnotix#177]
My IPTV provider has channel names like this: `|RU| Kinomiks 173`
On https://github.com/linuxmint/hypnotix/blob/master/usr/lib/hypnotix/xtream.py#L583 there is a check on first char and `|` is not passing this check so, almost all the channels are missing.
I tried to remove this check and then it works fine.

**Comment by superolmo** [comment]
@gromez Maybe changing **isalnum** to **isascii** is a better way to discard the subgroups. Maybe one day Hypnotix will be able to handle those too.

**Comment by gromez** [comment]
@superolmo yes, I confirm it's ok with `isascii`, all subgroups are categorized in _xEverythingElse_ group.
