### ISSUE TITLE
Recover original settings

### ISSUE THREAD

**Issue by eastrader** [linuxmint/hypnotix#18]
First thanks for the work on this!! Something I have been needing as I travel off shore.  That said this command -
gsettings set org.x.hypnotix providers "['Provider_Name:::https://m3u_url.m3u']"
that lets you add your own provider works, until the provider stops.
Then you are left with a total non function app. I was able to recover, not by a removal or re-install, not all the files get cleaned up.
I had another pc I was able to use gsettings list-recursively org.x.hypnotix to find how to recover the initial set up.
Maybe in the ReadMe info?
Again thanks for the hard work, if you pm me directly I would like to contribute some $'s.

**Comment by clefebvre** [comment]
That's done already. There's a preferences screen now and all the buttons to do just that :)
