### ISSUE TITLE
Wrong flag for Slovenia in TV Channels list

### ISSUE THREAD

**Issue by rumplin** [linuxmint/hypnotix#181]
How to reproduce:
1. start Hypnotix.
2. chose TV Channels.
3. see Slovenia with wrong flag.

Screenshot with wrong flag and application version

![Screenshot 2021-12-05 202516](https://user-images.githubusercontent.com/35449956/144760650-2a72e359-d756-4b6a-9752-3a32af9d9b83.png)

**Comment by rumplin** [comment]
Iraq is also missing it's flag, might just fix this also while you are at it.

**Comment by cloudykira** [comment]
Update to latest version **(2.1)**

![hypnotix](https://user-images.githubusercontent.com/91432991/144767105-da6ab045-34a9-419f-bd0e-0c6463612aba.png)

**Comment by rumplin** [comment]
Ok, disregard the bug and close it as invalid.
