### ISSUE TITLE
Why .hypnotix folder instead of using linux defaults?

### ISSUE THREAD

**Issue by miku86** [linuxmint/hypnotix#186]
Hey folks,

thanks for this cool application.

I'm just interested why the application uses `.hypnotix` in `HOME`, instead of using the linux defaults, e.g. `.cache`.
IMHO this approach clutters the `HOME` folder, without adding any benefits.

Greetings
Michael

**Comment by Axel-Erfurt** [comment]
It is completely normal to do it that way.

**Comment by miku86** [comment]
"Normal" doesn't imply "better".

What are the benefits of this approach?
Especially for an application that only uses the folder to cache data?

**Comment by qarkai** [comment]
Also see #201.
