### ISSUE TITLE
Error in make install

### ISSUE THREAD

**Issue by vimes666** [linuxmint/hypnotix#19]
I am trying to install Hypnotix from source.
I downloaded it, extracted it, went to the hypnotix-master directory and typed:
make
It gave a warning about languages with a hyphon in it. As it was just a warning I typed:
sudo make install
And this gave me the following error:
make: *** No rule to make target 'install'. Stop.
This often happens when you forget to do a ./configure, but there is no configure in hypnotix-master.
I tried it on mint mate 20 and lmde4 both with the same result.

What am I doing wrong?

**Comment by clefebvre** [comment]
If you're in Mint, use mint-build directly:

```
apt install mint-dev-tools
cd hypnotix
mint-build -i -g hypnotix
```

Or if you prefer the manual way:

```
apt install dpkg-dev git
git clone https://github.com/linuxmint/hypnotix.git
cd hypnotix
dpkg-buildpackage
sudo dpkg -i ../hypnotix*.deb
```

**Comment by vimes666** [comment]
Thanks Clem for the quick response. I used the first method and it worked as a treat :)
I like this project, thanks again.

**Comment by ItzSwirlz** [comment]
There *is* no make install task. It's just 'make', and essentially a manual install, like the Python nemo-extensions. There is nothing to compile or really do.

Now you could generate the desktop files but it requires a mint package (which I'm trying to see if I can get around that through my repo cinnamon-dev-tools to include stuff like mintcommon, but not have it be mint-specific).

You could add a make install task-which wouldn't be as annoying and would make the Debian packaging easier.

Feel free to open a PR if you wish.

**Comment by vimes666** [comment]
Thanks @ItzSwirlz but Clem already solved it for me.

**Comment by eggplants** [comment]
On Ubuntu 20, it works:
```bash
mkdir build_hypno && cd $_
git clone https://github.com/linuxmint/hypnotix.git --depth 1
cd hypnotix
dpkg-buildpackage -uc -us # avoid gpg error  
sudo dpkg -i ../hypnotix*.deb
cd ../../ && rm -rf build_hypno
```
