### ISSUE TITLE
Channel list hides w/o info when search doesn't return results

### ISSUE THREAD

**Issue by padovisky** [linuxmint/hypnotix#194]
When searching for a channel, the channel list panel disappears without showing any info when the query returns no results.
![Captura de tela de 2022-01-07 13-52-20](https://user-images.githubusercontent.com/37012/148578198-d84e56ca-df5f-4eda-8c73-19e23f6be2b1.png)
(ver 2.6)

**Comment by Axel-Erfurt** [comment]
no result = no list
clear the entry and hit ENTER

**Comment by padovisky** [comment]
> no result = no list clear the entry and hit ENTER

Ok, maybe I wasn't clear enough... What I'm saying is that i think the app should give some feedback to the user when the query returns no results. Hiding the list kinda breaks the layout, and looks more like something went wrong.  
I should say that its more a suggestion than a bug report.

**Comment by lulol** [comment]
This patch still won't keep the layout with the panel of channels but will show some feedback in the status bar and the console.

```
@@ -99,6 +99,7 @@
         self.active_channel = None
         self.fullscreen = False
         self.latest_search_bar_text = None
+        self.visible_search_results = 0
         self.mpv = None
         self.ia = IMDb()
 
@@ -572,14 +573,20 @@
             search_bar_text = unidecode(self.search_bar.get_text()).lower()
             label_text = unidecode(child.get_children()[0].get_children()[0].get_children()[1].get_text()).lower()
             if search_bar_text in label_text:
+                self.visible_search_results += 1
                 return True
             else:
                 return False
 
+        self.visible_search_results = 0
         self.channels_flowbox.set_filter_func(filter_func)
         if not self.channels_flowbox.get_children():
             self.show_channels(self.active_provider.channels)
-        self.status(None)
+        if self.visible_search_results == 0:
+            self.status(_("No channel name (of all %d) contains \"%s\". Clear the search box and press ENTER to restore the current list of channels.") % (len(self.channels_flowbox.get_children()), self.latest_search_bar_text))
+            print("No channel name (of all %d) contains \"%s\". Clear the search box and press ENTER to restore the current list of channels." % (len(self.channels_flowbox.get_children()), self.latest_search_bar_text))
+        else:
+            self.status(None)
         print("Filtering %d channel names containing the string '%s'..." % (len(self.channels_flowbox.get_children()), self.latest_search_bar_text))
         self.search_bar.set_sensitive(True)
         self.search_bar.grab_focus_without_selecting()
```
----
Tried to use the `set_placeholder()` function to keep a placeholder widget when there are no results, which should be available since libgtk 3.10 but I get `AttributeError: 'FlowBox' object has no attribute 'set_placeholder'` and the class help doesn't list the function either.

Also don't know if there is a better way to get the number of visible rows without having to count them in the filter function.

**Comment by Axel-Erfurt** [comment]
In Gtk you  should use **set_placeholder_text**

**Comment by lulol** [comment]
But isn't `set_placeholder_text` used with Gtk.Entry?

I was trying to use the placeholder for [ListBox](https://docs.gtk.org/gtk3/method.ListBox.set_placeholder.html). But now that you say that, I see that it wouldn't work with [FlowBox](https://docs.gtk.org/gtk3/class.FlowBox.html).

Well, I guess that it could be placed manually if really necessary.

**Comment by padovisky** [comment]
Hi @lulol ! Sorry for the delay.
I will close this issue, as the patch you made solved the lack feedback in the search.
