### ISSUE TITLE
Feature request: Fullscreen mode

### ISSUE THREAD

**Issue by starsep** [linuxmint/hypnotix#2]
It would be useful to have a fullscreen mode.
I'd imagine it could be enabled by keyboard shortcut or button in the bottom bar.

**Comment by jonathonf** [comment]
Closed by https://github.com/linuxmint/hypnotix/commit/c853d5483db7a0b64fd0160a8d6a8cb1c5fd4713

**Comment by ItzSwirlz** [comment]
Plus you can also "F11".

**Comment by starsep** [comment]
Works great, thanks!
