### ISSUE TITLE
[BUG] problem in managing channel thumbnails

### ISSUE THREAD

**Issue by dasaferi** [linuxmint/hypnotix#213]
I have encountered a problem in the cache of the channel icons, if I change the link to the icon via `tvg-logo="my new link"` this is not updated by hypnotix, I have not found a way to clear the cache of the icons downloaded by hypnotix, I have tried to re-add the playlist, but the result doesn't change. If, on the other hand, I change the title, the updated icon appears, but if I put the right one back, this old icon returns.
![immagine](https://user-images.githubusercontent.com/71762370/151664555-cfa7631d-84b7-4842-a519-3a810a136f17.png)

**Comment by superolmo** [comment]
The icons are saved under ~/.hypnotix/providers/
You may want to look in there, and possibly delete everything to wipe out the cache.

**Comment by qarkai** [comment]
Fixed in 2293de95baecd2838f687fb6e332a87f8276c969.

**Comment by dasaferi** [comment]
Thank you so much @qarkai , i close this issues.
