### ISSUE TITLE
Please remove the 1.1 deb

### ISSUE THREAD

**Issue by Axel-Erfurt** [linuxmint/hypnotix#214]
I've noticed that some of the issues created here have to do with some non-Mint users installing the deb file from releases. As this version is outdated it might be better to remove the file.

Perhaps a reference to newer versions in http://packages.linuxmint.com/pool/main/h/hypnotix/ would be better

**Comment by mrandersonsmith** [comment]
I managed to install on Ubuntu 22 Jellyfish by:

sudo add-apt-repository ppa:kelebek333/mint-tools
sudo apt update
sudo apt install hypnotix

**Comment by nafanz** [comment]
@mrandersonsmith 
Unfortunately, the version `4.6+klbknoble` offered there is already outdated, it would be good to update it to the current one.

Another problem is that I was able to install it only on Ubuntu 24.04, there is no version for 24.10 in the repository.
