### ISSUE TITLE
HYPNOTIX STOP WORKING - UBUNTU 20.04 AND GNOME 41 WAYLAND

### ISSUE THREAD

**Issue by bambinounos** [linuxmint/hypnotix#215]
Version 2.6 

[crashFile.txt](https://github.com/linuxmint/hypnotix/files/8074464/crashFile.txt)

**Comment by Axel-Erfurt** [comment]
try in terminal

`GDK_BACKEND=x11 hypnotix`

**Comment by bambinounos** [comment]
please check
![imagen](https://user-images.githubusercontent.com/65610134/154167716-a0d172bf-7a48-47d4-807d-121b6507825e.png)
![imagen](https://user-images.githubusercontent.com/65610134/154167886-990bd34f-66f9-46af-9dbd-c26ee18d3c68.png)
The address, user and password is ok

**Comment by Axel-Erfurt** [comment]
try to add

`vo=x11`

to the mpv options in hypnotix settings

**Comment by bambinounos** [comment]
Settings are
_hwdec=auto-safe;vo=x11_
Now the error has gone but it keeps loading and it does not play any media.
![imagen](https://user-images.githubusercontent.com/65610134/154261352-37f1e452-242a-44d6-a096-3108963cb97f.png)

**Comment by bambinounos** [comment]
I could see it freezes as well
![imagen](https://user-images.githubusercontent.com/65610134/154261936-f39bf138-f907-4c1a-be1a-2eccbc1b4660.png)

**Comment by Axel-Erfurt** [comment]
There is "authenticate failed" in your output. drm problem.

**Comment by bambinounos** [comment]
Do you mean address, username and pass of IPTV?

**Comment by Axel-Erfurt** [comment]
Maybe it's a graphics problem.
It seems that this problem appears more frequently under wayland.

try

`hwdec=no`

**Comment by bambinounos** [comment]
It did not work

**Comment by Azureit** [comment]
Does this problem happen with mpv?
run at the terminal `mpv -v [URL that your having problems]`
_________________________
Make sure you have vulkan and vaapi libraries installed for your GPU, and run `vulkaninfo` and `vainfo` to check for errors.
_________________________
`vo=x11` will disable hardware decoding, don't use it. Test my workaround for Wayland #205  (benefits: it will only work on a wayland session and will not disable hardware decoding)

**Comment by bambinounos** [comment]
Thanks for your help.
It was solved
Step 1, GPU driver had problems and I upgraded it.
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt upgrade
```
Step  2
I changed the hypnotix.py file #205 
Step 3
I changed hypnotix settings to `hwdec=vaapi`
Thanks again
