### ISSUE TITLE
Hypnotix does not run when libmpv2 is installed

### ISSUE THREAD

**Issue by tabascosw** [linuxmint/hypnotix#218]
As the title states, when libmpv2 is installed, hypnotix will no longer start, even when libmpv1 is still installed. This is an issue with opensuse Tumbleweed.

>   File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>
    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 531, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib64/libmpv.so.2: undefined symbol: mpv_detach_destroy

**Comment by Axel-Erfurt** [comment]
In my Mint there is no libmpv1 or libmpv2, only libmpv

`ldconfig -p | grep libmpv`

	libmpv.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpv.so.1
	libmpv.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpv.so

**Comment by tabascosw** [comment]
Ok, it is just a different naming in TW.
The package libmpv1 provides:
`/usr/lib64/libmpv.so.1
/usr/lib64/libmpv.so.1.109.0

The package libmpv2 provides:
`/usr/lib64/libmpv.so.2
/usr/lib64/libmpv.so.2.0.0`

So, as soon as libmpv.so.2 is present int the system, hypnotix won't run, even though libmpv.so.1 is also available. Maybe it is  just an issue with Tumbleweed.

**Comment by Axel-Erfurt** [comment]
Your libmpv.so.1 is missing the function _mpv_detach_destroy_

I have libmpv.so.1.107.0

**Comment by tabascosw** [comment]
I think it is actually libmpv.so.2 that is missing that function, because it is now depreciated, instead mpv_destroy is used.
`remove deprecated mpv_detach_destroy. Use mpv_destroy instead.`
I keep libmpv.so.2 off my system for the time being, I have a local copy of libmpv.so.1 that I can use, but it might be an issue for someone who wants to install hypnotix later on TW, libmpv.so.1 is no longer provided.
Thanks for your input.

**Comment by Axel-Erfurt** [comment]
`remove deprecated mpv_detach_destroy. Use mpv_destroy instead.`

You could change that in _mpv.py_

**Comment by tabascosw** [comment]
Yes, I just did this and it does solve the issue. Thanks again.
