### ISSUE TITLE
Still alive ?

### ISSUE THREAD

**Issue by linuxubuntu63** [linuxmint/hypnotix#223]
Hello.
Any new version planned ?

The project is still alive ?
Thanks

**Comment by ItzSwirlz** [comment]
Tons of development is still happening. There is no problem. The only app in danger being out of development is xplayer.

**Comment by linuxubuntu63** [comment]
I mean the hypnotix app.
Still no favourites and working search in vod.
The last version of hypnotix is 2.6 ?
Thanks

**Comment by linuxubuntu63** [comment]
Hello.
Do you have plan to add EPG,live tv favorites,movies favorites please ?
Thanks
