### ISSUE TITLE
African channels?

### ISSUE THREAD

**Issue by Alexxxis** [linuxmint/hypnotix#226]
Are you plannng to include africans channels (South Africa, Nigeria, Senegal, Ghana...) ?

**Comment by Axel-Erfurt** [comment]
Better ask this at https://github.com/Free-TV/IPTV. The list is maintained there.

**Comment by KAMI911** [comment]
@Alexxxis: did you open a PR there? Could we help somehow? Let's discuss the possibilities there: https://github.com/Free-TV/IPTV
Are there free channels from African channels? It is easy to add them if you go links for them. Also we are working on EPG support of the list.
