### ISSUE TITLE
Adding https://github.com/iptv-org/iptv

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/hypnotix#235]
Could you add https://github.com/iptv-org/iptv by default in Hypnotix, in next LM version ?

**Comment by Axel-Erfurt** [comment]
Why? You can add it in hypnotix if you need it.

If I look at the German list there, for example, many important free channels are missing.

**Comment by InfoLibre** [comment]
Default list in hypnotix is poor. [https://github.com/iptv-org/iptv](https://github.com/iptv-org/iptv) is the most complete list one can find on the web. It would be interesting to collaborate with this project, to complete the list and to add it by default in Hypnotix.

**Comment by Axel-Erfurt** [comment]
With illegal streams, it can happen very quickly that a repository is deleted from github.
Why should hypnotix risk that?

**Comment by InfoLibre** [comment]
Are a lot of streams illegal in https://github.com/iptv-org/iptv? Then, we could keep only legal streams from https://github.com/iptv-org/iptv and add them to Hypnotix.

**Comment by Axel-Erfurt** [comment]
You can do that yourself, in **your** hypnotix.

**Comment by KAMI911** [comment]
@InfoLibre , the default list in Hypnotix is here: https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8
We are trying to add as many free channels as possible. If you missing one please create a Pull Request (preferred) or fill a bug here:https://github.com/Free-TV/IPTV
