### ISSUE TITLE
Hypnotix does not load channels

### ISSUE THREAD

**Issue by heiler** [linuxmint/hypnotix#246]
Hypnotix does not load the channels from https://i.mjh.nz/PlutoTV/all.m3u8. Starting Hypnotix in a terminal session I see:
```
Pluto TV All: Getting playlist...
'content-length'
Pluto TV All: Failed to Download playlist from Pluto TV All"
```

**Comment by lulol** [comment]
A fix for this issue is already merged in the master. #241

It's due that the site replies to hypnotix using `Transfer-Encoding` in chunked mode without 
a `content-length` header.
