### ISSUE TITLE
Back Arrow isn't exactly drawn to theme

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/hypnotix#25]
I am using the Yaru-Dark theme on my GNOME right now-and I'm pretty sure themes have support for images with arrows... and although the color is orange too, I don't think this is correct.

It should pull this out of the theme.

See image
![Screenshot from 2020-11-23 11-08-43](https://user-images.githubusercontent.com/24401303/99985904-8a096c00-2d7c-11eb-9039-8c8d9b846848.png)

**Comment by clefebvre** [comment]
The icon comes from the icon theme, its name is go-left-symbolic.

**Comment by JosephMcc** [comment]
This was fixed by https://github.com/linuxmint/hypnotix/pull/39
