### ISSUE TITLE
Can't add EPG when my list is in file

### ISSUE THREAD

**Issue by PrzemekSkw** [linuxmint/hypnotix#267]
Hello, I noticed that Hypnotix don't show option to add EPG when I have channels list added from local file. Can be that changed or I must host my file for example on my nextcloud server and add link?

**Comment by Axel-Erfurt** [comment]
Haven't you noticed that hypnotix doesn't support EPG yet?

**Comment by PrzemekSkw** [comment]
There's field for EPG when I choose to add url channels list.

**Comment by Axel-Erfurt** [comment]
This field has no function yet.

**Comment by PrzemekSkw** [comment]
OK, thanks. 
PS. Do You now how can I host my m3u channel list file that I can share URL?

**Comment by Axel-Erfurt** [comment]
Create a public gist and share the raw file link.

**Comment by PrzemekSkw** [comment]
Thanks
