### ISSUE TITLE
How to proplerly add MPV Options

### ISSUE THREAD

**Issue by tacosuzy** [linuxmint/hypnotix#27]
Hello, I am very happy so far with performance. I am wondering how does one correctly add mpv options? I've added my settings into the mpv options spot separated by commas and space ", " but they didn't take affect. I've tried with the settings separated by a comma setting,setting" but that didn't work either.

Here are the options I'm trying to add.

MOUSE_BTN3 ignore
MOUSE_BTN4 ignore

These options disable seeking of playing media with the mouse scroll wheel. 

I have these in use in my current mpv install located in /etc/mpv I wonder if there's a way to select the files or link the conf files to the mpv when in use with the app.

If not known these specific settings go into a document called input.conf in /etc/mpv

**Comment by ichristophe56** [comment]
On peut rajouter dans ce cas Libmpv1 via synaptic

**Comment by tacosuzy** [comment]
@ichristophe56 Was that response for me or the creators? I see that is a video player but I'm unsure what you mean if you're response was for me.

**Comment by linuxundich** [comment]
You need to enter the [mpv-options](https://mpv.io/manual/master/) in pairs like this...

```
hwdec=auto-safe rtsp-transport=udp deinterlace=yes
```

...no commas in between and always `option=value` like `deinterlace=yes` even when just the option (like `deinterlace`) would be enough.

**Comment by linuxundich** [comment]
Hi Clement, a description under the dialogue would be a nice to have. I had the same problem and went through the source code to figure out, what I had to do.
