### ISSUE TITLE
V. 3.3: Pre-set to dark mode causes problems in opensuse

### ISSUE THREAD

**Issue by tabascosw** [linuxmint/hypnotix#278]
The new preferred setting to dark mode causes issues in my openSuse TW, the program would not start. Disabling that setting makes the program run again.
Here is the line from usr/lib/hypnotix/hypnotix.py that I had to change. Not sure if others are effected as well. Setting it just to false won't work, Hypnotix will then not start.

       ##self.dark_mode_manager = XApp.DarkModeManager.new(prefer_dark_mode=True)

The previous version with the dark mode switch works without an issue.

Maybe I am missing a lib, but all requirements that are mentioned have been met.

**Comment by mtwebster** [comment]
What version of libxapp are you using? You need 2.6.  What happens if you run `hypnotix` from a terminal?

**Comment by tabascosw** [comment]
Currently only version 2.4 is available and this is probably the issue.
Starting from a terminal:

AttributeError: 'gi.repository.XApp' object has no attribute 'DarkModeManager'

**Comment by mtwebster** [comment]
https://github.com/linuxmint/hypnotix/commit/fd22e655f819d907754b857ebe3b964f709d3ac1
