### ISSUE TITLE
After update to Hypnotix 3.4, App do not start

### ISSUE THREAD

**Issue by hamdi-kadri** [linuxmint/hypnotix#279]
Environment: Manjaro - 6.3.5-2-MANJARO (64-bit) - KDE Plasma 5.27.5
I did manage to solve it by commenting this line in /usr/lib/hypnotix/hypnotix.py:
`self.dark_mode_manager = XApp.DarkModeManager.new(prefer_dark_mode=True)`

Error: 
`(hypnotix.py:3532): Gtk-WARNING **: 15:26:28.844: Theme directory actions/16-Dark of theme Zafiro-Icons-Dark-Black-f has no size field

Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 109, in activate
    window = MainWindow(self)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/hypnotix/hypnotix.py", line 309, in __init__
    self.dark_mode_manager = XApp.DarkModeManager.new(prefer_dark_mode=True)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.XApp' object has no attribute 'DarkModeManager'`

**Comment by mtwebster** [comment]
https://github.com/linuxmint/hypnotix/issues/277
