### ISSUE TITLE
Hypnotix icon [feature request]

### ISSUE THREAD

**Issue by Hilyxx** [linuxmint/hypnotix#285]
Hey
I like this app and i made an icon. Not perfect but it's cool.
You can use it if you want. (svg 64 and 128)

![Capture d’écran du 2023-07-15 21-00-14](https://github.com/linuxmint/hypnotix/assets/21991448/270a88cb-d5f7-4584-a343-00d48101e69c)
[hypnotix.zip](https://github.com/linuxmint/hypnotix/files/12062535/hypnotix.zip)

**Comment by DYefremov** [comment]
Hi,
 Can I use your icon for my fork?

**Comment by Hilyxx** [comment]
Hi
yes of course
