### ISSUE TITLE
Feature request: Plugin or Addon in python to be able to use web scraping

### ISSUE THREAD

**Issue by kodi-rc** [linuxmint/hypnotix#29]
Feature request: Plugin or Addon in python to be able to use web scraping [html request, beautifulsoup, regex, etc ...] and thus create the links at run time with the content that was extracted from html pages.

Because it is very common for live video links to have tokens that expire daily.
And using web scraping makes it easy to capture that link with token at run time

In a similar way as with Kodi addons.

For example, a fixed list would be created with
name, logo, group and a 'URL for Scraping'

Then this 'URL for Scraping' would be manipulated by a Python script and would return the link of the media file to be played.

------
URL for Scraping:
https://redecanaistv.com/assistir-sbt-online-24-horas-ao-vivo_8a0548907.html

Video link after web scraping:
https://streaming.belugacdn.link/a/hls1/sbt.m3u8?expires=1606600451&token=a1a5f40f1926bcd0a444f079caaae5e6

**Comment by clefebvre** [comment]
That's beyond the scope, I'm sorry.
