### ISSUE TITLE
URL label enlarges the window

### ISSUE THREAD

**Issue by Axel-Erfurt** [linuxmint/hypnotix#297]
If the link text is very long, the window will be enlarged in width so that no video can be seen.
It also cannot be reduced in width.

**Comment by umikali222** [comment]
Which link text? Could you add some screenshots?

**Comment by Axel-Erfurt** [comment]
link text above video

short link text
![hyp_1](https://github.com/linuxmint/hypnotix/assets/2623542/c762c216-6283-4266-b0d1-ae80b3b8063c)

long link text
![hyp_2](https://github.com/linuxmint/hypnotix/assets/2623542/0152670c-2a3e-4520-9c5e-fd0a8223f45d)
