### ISSUE TITLE
Streams in Wayland Session not working

### ISSUE THREAD

**Issue by ELT4N1N** [linuxmint/hypnotix#33]
Hi together,

i can't open streams if Hypnotix is started in a Wayland session like sway.
A workaround for now is to force Hypnotix to use XWayland: env GDK_BACKEND=x11 hypnotix

Here is the error output:
```
  File "/usr/lib/hypnotix/hypnotix.py", line 1018, in on_mpv_drawing_area_realize
    self.reinit_mpv()
  File "/usr/lib/hypnotix/hypnotix.py", line 1039, in reinit_mpv
    input_vo_keyboard=True,osc=True, ytdl=True, wid=str(self.mpv_drawing_area.get_window().get_xid()))
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
CHANNEL: 'Das Erste HD' (https://mcdn.daserste.de/daserste/de/master_3744.m3u8)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/hypnotix/hypnotix.py", line 591, in play_async
    self.reinit_mpv()
  File "/usr/lib/hypnotix/hypnotix.py", line 1039, in reinit_mpv
    input_vo_keyboard=True,osc=True, ytdl=True, wid=str(self.mpv_drawing_area.get_window().get_xid()))
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
```

**Comment by tomastan** [comment]
Confirming issue on Ubuntu 20.10

**Comment by tacosuzy** [comment]
I can confirm this with EndeavourOS using gnome. When switching to xorg before logging on the program functions normally. 

Another note when using EndeavourOS KDE the streams play normally without needing to change anything. I do not know if wayland is enabled by default in the KDE EndeavourOS though.

I did however get streams to play under wayland by running hypnotix in sudo but could not add another playlist. Maybe that info can be helpful.

**Comment by linuxundich** [comment]
Another confirmation of this issue with Gnome 3.38.2 under Arch Linux. When started under Wayland, the program fails zu start the stream.

**Comment by mbilotta** [comment]
Had the same problem with Manjaro Linux GNOME 20.2. Starting hypnotix from the terminal this way:
```
$ GDK_BACKEND=x11 hypnotix
```
fixed the problem for me at the cost of having the stream played in another window.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/hypnotix/commit/1081138e58012706217fe5b492e571fc0771c2f9
