### ISSUE TITLE
Dependency is not satisfiable: python3-imdbpy

### ISSUE THREAD

**Issue by dwvisser** [linuxmint/hypnotix#34]
I assume this is because I'm still using Linux Mint 19.3, which is Ubuntu Bionic-based and the python3-imdbpy APT package [appears in Ubuntu repos starting at Ubuntu Focal](https://packages.ubuntu.com/focal/python3-imdbpy). Is there a way to install from the source tarball?

**Comment by Hedronmx** [comment]
you can install the deb from the 20.04 repo

i have installed it in 18.04

**Comment by ricksdunn** [comment]
I checked a Ubuntu machine I have on 20.04 and it doesn't show up in the repo...? What specific repo are you using to grab this .deb ??

**Comment by Hedronmx** [comment]
https://packages.ubuntu.com/focal/all/python3-imdbpy/download

Click on any mirror

**Comment by dwvisser** [comment]
Thank you @Hedronmx! That solved my installation issue.
