### ISSUE TITLE
No movies?

### ISSUE THREAD

**Issue by RvEEK** [linuxmint/hypnotix#35]
Hypnotix does not recognize movies and drops them under TV channels. Series are working fine.

![afbeelding](https://user-images.githubusercontent.com/52418660/100876097-3814c480-34a7-11eb-804f-9d1b1dbfd4a2.png)

**Comment by kodi-rc** [comment]
@RvEEK Could you provide an example of how your list is, both series and films?
thanks

**Comment by clefebvre** [comment]
Covered by https://github.com/linuxmint/hypnotix/issues/47
