### ISSUE TITLE
Removal of some Japanese TV Bundles

### ISSUE THREAD

**Issue by Linuxzun** [linuxmint/hypnotix#351]
I would like to address a concern regarding the inclusion of certain TV streams in the Hypnotix application, particularly those involving Japanese TV stations such as NHK. NHK requires viewers to pay a license fee, and streaming Japanese television content may violate copyright laws without proper permissions.

According to the Japan Commercial Broadcasters Association, broadcasting TV programs over the internet requires explicit permission from broadcasters and program creators, covering reproduction rights and public transmission rights. Failure to obtain these permissions may constitute a breach of copyright law in Japan. This includes unofficial distribution of copyrighted content, which is currently a concern with some of the curated streams available in Hypnotix.

There is historical precedent with Linux Mint in Japan regarding issues related to intellectual property rights. For instance, in 2012, Japanese mirror servers suspended the distribution of Linux Mint due to the inclusion of proprietary codecs. Though the situation was resolved, there remains a sensitivity around compliance with local laws.

In light of these concerns, I respectfully request that the bundles of Japanese TV stations be removed from Hypnotix to ensure the legal use of Linux Mint in Japan.

Thank you for your understanding and attention to this matter.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/hypnotix?tab=readme-ov-file#tv-channels-and-media-content
