### ISSUE TITLE
Feature request : add to favorites

### ISSUE THREAD

**Issue by enigma131** [linuxmint/hypnotix#36]
Great app! All is in the title...

**Comment by Axel-Erfurt** [comment]
You can make your own m3u with your favourites and add it in hypnotix.

**Comment by Heclalava** [comment]
I think also adding to favourites would be great, especially if using Xtreme codes API and you aren't using and m3u file/link

**Comment by puigpuig** [comment]
Yes, having such a long list of TV stations is excellent, but it would be useful to have a Favorites list of TV stations to go to those one uses ordinarily. 

Thank you!!

**Comment by LinuxOnTheDesktop** [comment]
> it would be useful to have a Favorites list of TV stations to go to those one uses ordinarily.

I second this. Otherwise, one spends time fruitlessly, again and again - especially since, so far as I can tell, the list of services-by-country (e.g. UK, India, etc.) is in completely random order.

**Comment by LobotomyTH** [comment]
> You can make your own m3u with your favourites and add it in hypnotix.

Yeah, but that's a huge pain in the rear, isn't it? It's a nice workaround for now, but it's hardly intuitive.

**Comment by clefebvre** [comment]
We'll add favorites in the future. Closing the issue.
