### ISSUE TITLE
Doesn't start on Debian Buster

### ISSUE THREAD

**Issue by ChojinDSL** [linuxmint/hypnotix#38]
I've tried the released .deb file as well as compiling from source by myself. 
It builds ok, just when I try to run it, I get the following.

`Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 64, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 92, in __init__
    self.builder.add_from_file(gladefile)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/hypnotix/hypnotix.ui:846:1 Invalid object type 'XAppStackSidebar' (6)`

I'm guessing there is some dependency that's missing on debian?

**Comment by Pablohn26** [comment]
Same problem here too

**Comment by knkp1996** [comment]
I am also facing same issue. Just downloaded the deb package from repo and installed on MXLinux19.3. The application is not starting. Not able to see in task manager too.

**Comment by prog-amateur2** [comment]
I have tested and it doesn't work for me neither.

**Comment by ItzSwirlz** [comment]
Did you guys ensure you have all Xapp libraries installed?

**Comment by ChojinDSL** [comment]
Can you be specific as to which xapp libraries need to be installed?

I installed all the xapp libs I found on Debian, but that doesn't make a difference. Either way, compilation succeeds without complaining. But in the end when running the app, it produces the same error message as in my original post.

**Comment by mtwebster** [comment]
Buster's xapp package is too old (1.2) - you need 1.4 at least.

**Comment by clefebvre** [comment]
A requirements section was added to README.
debian/control also now requires version 1.4+ of libxapp.
