### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by rizet** [linuxmint/hypnotix#4]
![image](https://user-images.githubusercontent.com/63219214/97808235-bd505380-1c33-11eb-9a7a-84bc49cfa979.png)
It just doesn't work. There are no context menus or anything otherwise to help with that.

**Comment by jotisa** [comment]
Did you try clicking on the lower box for a specific channel?  I got most of them working, except the ones pointing to plugin.  You could also try opening a terminal and launching $ hypnotix from there to see what output you get, and please check you do have internet.
![image](https://user-images.githubusercontent.com/22183762/97826651-2ebdef80-1c90-11eb-9e5b-2de11271f3f0.png)

**Comment by rizet** [comment]
Yes, I did try that. And yes, I do have internet, as you can see I have an active web browser open ffs

**Comment by rizet** [comment]
i tried again it just magically started working wtf
