### ISSUE TITLE
it doesn't start in Debian 10.6 Cinnamon

### ISSUE THREAD

**Issue by fernandofvh** [linuxmint/hypnotix#46]
Hello. I have tried Hypnotix from .deb arcchive and it is supossed to be install but in terminal I have got this answTraceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 64, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 92, in __init__
    self.builder.add_from_file(gladefile)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/hypnotix/hypnotix.ui:846:1 Invalid object type 'XAppStackSidebar' (6)
 Any solution? Thank you very much.

**Comment by clefebvre** [comment]
You need a more modern version of libxapp (if I remember well 1.4 or higher).

**Comment by fernandofvh** [comment]
Hello. So I will try that solution. Thank you very much.
