### ISSUE TITLE
won't edit nor remove providers

### ISSUE THREAD

**Issue by D-EVE-R** [linuxmint/hypnotix#49]
hello please fix this issue i don't know am i the only one who's facing this problem or not but anyway the app won't edit nor remove providers the only option to do it is to reset to defaults

**Comment by scoson** [comment]
I can confirm.. I went back to previous build built from source.

**Comment by D-EVE-R** [comment]
> I can confirm.. I went back to previous build built from source (11-23).

but as far as I know, the previous one doesn't have the preferences nor providers option I guess

**Comment by tacosuzy** [comment]
I can confirm I am unable to remove the free providers. When clicking the delete button nothing happens. Not a deal breaker just informing my experience.

**Comment by D-EVE-R** [comment]
> I can confirm I am unable to remove the free providers. When clicking the delete button nothing happens. Not a deal breaker just informing my experience.
> 
> Edit: If it is a distro specific issue I am running endeavouros with KDE and now gnome.
> 
> Also I am using version 1.1-3

no there is nothing to do about the distro the problem is in the app itself am using Linux mint
about the version, there are only 2 releases 1.0 and 1.1

**Comment by clefebvre** [comment]
Can you run it from terminal and see if you get an error when removing the provider?

**Comment by scoson** [comment]
Clem, I just installed 20.1 beta from iso, and in the default 1.3 build provided, I was able to add my own local file (which is just 4 of the American channels from the freeiptv edited into 1 file) just fine from the providers tab. But also from the providers tab, Ticking edit or remove appears to do nothing, iptv provider still shows. However, when on the home tab, the channel count is now correct as well as only showing the 4 channels from my local file when tv channels tab is opened. I believe this might have occured after restarting the app? I will add that I didn't try your suggestion in your comment as I only saw the command from your Oct monthly to add a channel, not sure about removing, sorry.

**Comment by D-EVE-R** [comment]
> Can you run it from terminal and see if you get an error when removing the provider?

yes it does this is the output

Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 774, in on_delete_button_clicked
    self.navigate_to("delete_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_hypnotix_hypnotix.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 774, in on_delete_button_clicked
    self.navigate_to("delete_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'

**Comment by scoson** [comment]
I don't know if this is any help at all (D-EVE-R's error message may be all you needed and there's already a fix), but when Hypnotix built from commits on Nov 23, 2020 (I followed instructions given to build in issue #19) everything works properly. 
I'm not good at github but now I know what "run it from the terminal" means for troubleshooting lol, Thanks D-EVE-R, was same error for me.

**Comment by Axel-Erfurt** [comment]
in hypnotix.py line 775 and 801  remove **name=** 

775

```self.navigate_to("delete_page", provider.name)```

801

```self.navigate_to("add_page", provider.name)```

**Comment by scoson** [comment]
> in hypnotix.py line 775 and 801 remove **name=**
> 
> 775
> 
> `self.navigate_to("delete_page", provider.name)`
> 
> 801
> 
> `self.navigate_to("add_page", provider.name)`
> 
> and you can edit and delete

This worked, whoop whoop!
I'm on Mint 20.1 beta using version 1.3. 
The lines for me were 774 and 799.

**Comment by D-EVE-R** [comment]
> in hypnotix.py line 775 and 801 remove **name=**
> 
> 775
> 
> `self.navigate_to("delete_page", provider.name)`
> 
> 801
> 
> `self.navigate_to("add_page", provider.name)`
> 
> and you can edit and delete

my lines were different but it worked anyway thanks for your replay

**Comment by drewb0y** [comment]
Using the fix above I was able to delete, but not add an XTream provider. Adding by M3U Url works.
