### ISSUE TITLE
Keyboard Shortcuts Need Update

### ISSUE THREAD

**Issue by jotisa** [linuxmint/hypnotix#5]
The Keyboard Shortcuts Menu could use some update, or point to where to edit them, starting with themself ctrl + k for keyboard shortcuts.  Many thanks for the great work.

**Comment by clefebvre** [comment]
We'll add more as we go along. So far we only have fullscreen. We'll have more when we redirect key events towards mpv.

**Comment by jotisa** [comment]
Thanks!
