### ISSUE TITLE
Unable to run hypnotix

### ISSUE THREAD

**Issue by RitamChakraborty** [linuxmint/hypnotix#50]
I installed the deb package provide with `dpkg`. First it was missing the `requests` module. So I installed it using pip. But after that, having this error running it through terminal.

```
Traceback (most recent call last):                                                                          
  File "/usr/lib/hypnotix/hypnotix.py", line 64, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 92, in __init__
    self.builder.add_from_file(gladefile)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/hypnotix/hypnotix.ui:846:1 Invalid object type 'XAppStackSidebar' (6)
```
And nothing is happening after that.

**Comment by kodi-rc** [comment]
The same error occurs on Raspberry Pi OS with desktop
https://www.raspberrypi.org/software/operating-systems/

**Comment by clefebvre** [comment]
You need libxapp 1.4+.

A requirement section was added to the README today.
