### ISSUE TITLE
Build for Fedora?

### ISSUE THREAD

**Issue by x011** [linuxmint/hypnotix#53]
Is it possible to build for Fedora? If so, would you be kind enough to share the necessary steps?
Thank you.

**Comment by tacosuzy** [comment]
I tried to get this running on fedora but was unsuccessful as I am not fully technical in linux currently. I like gnome so I installed endeavouros with gnome to be able to use hypnotix.

**Comment by clefebvre** [comment]
Hi,

It should be easy enough. No compilation is necessary since it's all in python. You just need a Fedora maintainer or someone who's willing to make an RPM for it.

If they have any technical question we'll be happy to help.

**Comment by dilipkonline** [comment]
Friends,
Till an rpm is available hope this helps :  https://github.com/dilipkonline/Fedora33-Hypnotix-IPTV

**Comment by dilipkonline** [comment]
> Is it possible to build for Fedora? If so, would you be kind enough to share the necessary steps?
> Thank you.

Friends,
Till an rpm is available hope this helps : https://github.com/dilipkonline/Fedora33-Hypnotix-IPTV

**Comment by dilipkonline** [comment]
> I tried to get this running on fedora but was unsuccessful as I am not fully technical in linux currently. I like gnome so I installed endeavouros with gnome to be able to use hypnotix.

Friends,
Till an rpm is available hope this helps : https://github.com/dilipkonline/Fedora33-Hypnotix-IPTV

**Comment by dtantsur** [comment]
@clefebvre the current layout Hypnotix uses will make it quite hard to create a proper package. Like, hardcoding `/usr/lib/hypnotix/hypnotix.py` is probably a no-go, Python stuff goes to `/usr/lib/python3.x/site-packages` (I think you'll have the same issues with any other distribution tbh). For the same reason it cannot be used in a virtual environment.

May I suggest you add an actual setup.py and make `/usr/bin/hypnotix` work via an import?

**Comment by dtantsur** [comment]
I started looking into a potential package, and immediately hit the problem that python-imdb was retired from Fedora :( https://bugzilla.redhat.com/show_bug.cgi?id=1627219

**Comment by atrias** [comment]
> > Is it possible to build for Fedora? If so, would you be kind enough to share the necessary steps?
> > Thank you.
> 
> Friends,
> Till an rpm is available hope this helps : https://github.com/dilipkonline/Fedora33-Hypnotix-IPTV

Thank you for this

I also had to `dnf install python-setproctitle`
