### ISSUE TITLE
Ubuntu BIONIC Dependency is not satisfiable: python3-imdbpy

### ISSUE THREAD

**Issue by ricksdunn** [linuxmint/hypnotix#55]
Unable to attempt to correct this deficiency ...
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ sudo apt search python3 | grep -i imdb
<<empty>>

https://lists.archive.carbon60.com/mythtv/commits/629355 << echos the issue below with 18.04 BIONIC >>
** although on another entity others attempting to use mythtv are also experiencing the same ... **

<<snippet>>
python3-imdbpy is not available for *ubuntu 18.04 (Bionic) as a result
mythtv-frontend from ppa:mythbuntu/31 will not install.
<<snippet>>

**Comment by clefebvre** [comment]
The package can be obtained from focal: http://ftp.osuosl.org/pub/ubuntu/pool/universe/i/imdbpy/python3-imdbpy_6.8-2_all.deb

**Comment by ItzSwirlz** [comment]
That's not really a good idea but whatever.
