### ISSUE TITLE
Kubuntu/KDE neon problem with hypnotix 1.1

### ISSUE THREAD

**Issue by dasaferi** [linuxmint/hypnotix#56]
I have test this program with Kubuntu 20.04.1 LTS and KDE neon 20.04 LTS always based on ubuntu.
I installed the deb file via qapt-deb-installer to simplify the dependency search operation, the installation was done without any problem.
The program once opened shows the main screen as in the photos in the main page of github, but once chosen a country "freezes" as in the following screen, I can go back without any problem only that I can't play any video stream.
![Screenshot_20201205_193042](https://user-images.githubusercontent.com/71762370/101260468-7244c700-3730-11eb-9d2a-a30fcdaa4d2d.png)
I can't understand what it depends also because I don't receive any crash or block the application.

**Comment by PaulBrand63** [comment]
There appears to be a missing dependency - "python3-gi-cairo".  Install that and it will work.

**Comment by dasaferi** [comment]
> There appears to be a missing dependency - "python3-gi-cairo". Install that and it will work.

Thank you so much now works hypnotix.
At this point i close issues.
