### ISSUE TITLE
1.0.0 deb package from blog missing libmpv1 dependency

### ISSUE THREAD

**Issue by hs123org** [linuxmint/hypnotix#6]
I didn't have libmpv1 installed when I installed the deb package mentioned on https://blog.linuxmint.com/?p=3978
App didn't start with rather obvious error message. Installing libmpv1 manually fixed the issue.

Current Linux Mint 20 with up to date packages.

**Comment by ichristophe56** [comment]
Lib
Libmpv1 sinon erreur effectivement
