### ISSUE TITLE
[Feature Request] Add provider kodinerds-iptv

### ISSUE THREAD

**Issue by freddii** [linuxmint/hypnotix#67]
It would be handy to have the provider kodinerds-iptv.

https://github.com/jnk22/kodinerds-iptv

Name: Kodinerds Clean
Type: M3U URL
URL: http://bit.ly/kn-clean

**Comment by Axel-Erfurt** [comment]
You can download the file and add it in hypnotix

for example

https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/clean/clean.m3u
