### ISSUE TITLE
Hypnotix freezes when I try to open a channel in Kubuntu 20.04

### ISSUE THREAD

**Issue by hmslima** [linuxmint/hypnotix#69]
When I click in the `TV Channels` button, I get these messages:

```
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/austria.png
[...]
[...]
[...]
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/music.png
```

The fact that the program is not loading these badges is not a big deal and this is not the actual problem reported in this thread, but I thought that it would be good to talk about it.

**HERE IS THE REAL PROBLEM**, when I try to open any channel, I get this in the terminal...

```
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 293, in on_category_button_clicked
    self.show_channels(group.channels)
  File "/usr/lib/hypnotix/hypnotix.py", line 323, in show_channels
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, self.window.get_scale_factor())
TypeError: Couldn't find foreign struct converter for 'cairo.Surface'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

... and then the program freezes, but I can easily close it.

<hr>

I have to say that I don't live in the USA but in Brazil, so I don't know if it affects in something, although I've tried channels from Afghanistan, Norway, France, Portugal, China, etc, and I got this very same message.

**Comment by mtwebster** [comment]
You may be missing a dependency - try installing `python3-gi-cairo`.

If that fixes it I'll update the packaging.

**Comment by hmslima** [comment]
**It solved BOTH problems!** 😃

I was expecting only the solution for the second (and most important) problem of freezing, but the flags were loaded too.
