### ISSUE TITLE
Feature request: xtream support

### ISSUE THREAD

**Issue by omlet05** [linuxmint/hypnotix#7]
ability to connect directly with server url, login & password using xtream API

**Comment by clefebvre** [comment]
Isn't that the same as an M3U link where the login and password are passed as arguments?

**Comment by omlet05** [comment]
Indeed it is simply a M3u like this one http://example.com:80/get.php?username=USER&password=PASS&type=m3u_plus&output=ts

**Comment by clefebvre** [comment]
Ok then that's already supported. We'll be adding a UI for preferences shortly but you can already put that in gsettings.
