### ISSUE TITLE
Cannot be installed on Elementary OS 5.1.7 Hera (based on Ubuntu 18.04.04 LTS)

### ISSUE THREAD

**Issue by GabiBCN** [linuxmint/hypnotix#70]
![WhatsApp Image 2020-12-11 at 22 13 06](https://user-images.githubusercontent.com/53320661/101957223-55613580-3c01-11eb-97b2-a80896f778d2.jpeg)
![WhatsApp Image 2020-12-11 at 22 25 12](https://user-images.githubusercontent.com/53320661/101957230-585c2600-3c01-11eb-8da5-09f6a0c9d19b.jpeg)

**Comment by Axel-Erfurt** [comment]
Maybe you can install the python3-imdbpy deb package from https://www.ubuntuupdates.org/package/core/bionic/universe/base/python-imdbpy

**Comment by rivermonk** [comment]
Doesn't run in XUbuntu 18.04 either due to same unresolved dependency. tried AxelpErfurt link above, but that is for already installed python. Evidently Hypnotix needs python 3. Any work around? I don't want to upgrade to 20.04 yet, due to third party programs I like.

**Comment by Axel-Erfurt** [comment]
If you don't need that imdb thing you can try my [hypnotixLite Version.](https://github.com/Axel-Erfurt/hypnotixLite)

It does not have to be installed, can be started directly from the folder and has no dependencies on xapps libraries.
