### ISSUE TITLE
"Edit" and "Delete" buttons for the provider do not work

### ISSUE THREAD

**Issue by merwizard** [linuxmint/hypnotix#78]
Version:  1.3 (tag)
Reproduction: (Optional step:) Add a new provider. Used a local m3u file, Try to edit it after succesful adding
     No visible result when clicking. The following traceback appears in the terminal:
     
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 799, in on_edit_button_clicked
    self.navigate_to("add_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'

The same behavior is recorded when trying to delete the provider.

Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 774, in on_delete_button_clicked
    self.navigate_to("delete_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'

**Comment by Axel-Erfurt** [comment]
[#49](https://github.com/linuxmint/hypnotix/issues/49#issuecomment-747552974)

**Comment by ava57r** [comment]
version: 1.4 

```console
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 799, in on_edit_button_clicked
    self.navigate_to("add_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'
```

**Comment by Axel-Erfurt** [comment]
> version: 1.4
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/hypnotix/hypnotix.py", line 799, in on_edit_button_clicked
>     self.navigate_to("add_page", name=provider.name)
> TypeError: wrapper() got an unexpected keyword argument 'name'
> ``

the solution is above your post

**Comment by ava57r** [comment]
@Axel-Erfurt Thanks.
I will wait for the update.

**Comment by Axel-Erfurt** [comment]
You can also try the deb from my fork. I have already corrected the mistake there.

https://github.com/Axel-Erfurt/hypnotix/releases/tag/1.3

**Comment by clefebvre** [comment]
https://github.com/linuxmint/hypnotix/commit/6bf28b98e3fa20a9825fb136079f280fb91aab6e
