### ISSUE TITLE
Quitting Hypnotix while a video is playing triggers a segfault

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/hypnotix#82]
Quitting Hypnotix while a video is playing triggers a segfault.  Even if you go into the player interface and stop (pause) the video, it will still crash.  Issue seems to be that it is still caching the video even when it is stopped (paused).  There does not seem to be a way to stop the background activity before quitting the program.

System Reports Crash reports and Stack trace are empty.
Failure is repeatable.  Hypnotix is quit using Ctrl+Q or the by the menu.
System is extremely stable (Linux Reference Test System) and segfaults are very rare.
Please see the attached files.

[system-information.txt](https://github.com/linuxmint/mint20.1-beta/files/5740567/system-information.txt)
[dmesg-1.txt](https://github.com/linuxmint/mint20.1-beta/files/5740568/dmesg-1.txt)
[core-dump-1.txt](https://github.com/linuxmint/mint20.1-beta/files/5740569/core-dump-1.txt)
[dmesg-2.txt](https://github.com/linuxmint/mint20.1-beta/files/5740571/dmesg-2.txt)
[core-dump-2.txt](https://github.com/linuxmint/mint20.1-beta/files/5740572/core-dump-2.txt)
[dmesg-3.txt](https://github.com/linuxmint/mint20.1-beta/files/5740573/dmesg-3.txt)
[core-dump-3.txt](https://github.com/linuxmint/mint20.1-beta/files/5740575/core-dump-3.txt)

**Comment by Harry-W-Haines-III** [comment]
Just a follow up on this.  During the Beta testing window, I was not able to test on this computer because it is hosting a streaming radio service and needs minimal downtime.  Late last night I did a clean install of Mint 20.1 Cinnamon Edition.  Still seeing a core dump in the journald log when Hypnotix is closed.  The hardware is slightly different and using the latest NVIDIA 460.32.03 drivers.  I've attached the system info coredump and dmesg.

[system-information.txt](https://github.com/linuxmint/hypnotix/files/5791160/system-information.txt)
[core-dump.txt](https://github.com/linuxmint/hypnotix/files/5791161/core-dump.txt)
[dmesg-error.txt](https://github.com/linuxmint/hypnotix/files/5791162/dmesg-error.txt)

**Comment by Harry-W-Haines-III** [comment]
Today I did a clean install with all the updates on an Intel CPU/GPU based laptop.  The failure previously noted on two other systems did not occur.
[system-information.txt](https://github.com/linuxmint/hypnotix/files/5844205/system-information.txt)

**Comment by Harry-W-Haines-III** [comment]
Update on this issue.  I found that if you return to the starting page of the application and stop the player and then close the application, the segfaults do not occur on the NVidia systems.  Everything exits cleanly.  See the attached screen shot.
![Screenshot-from-2021-02-23-07-44-06](https://user-images.githubusercontent.com/45599505/108845526-89ff4f00-75ab-11eb-8568-1ef05ceb1315.png)

**Comment by clefebvre** [comment]
I'll close this. I'm not sure what to do to be honest, it looks like a driver/mplayer issue.
