### ISSUE TITLE
I created a patch for debian buster support

### ISSUE THREAD

**Issue by paledega** [linuxmint/hypnotix#84]
I created a patch for debian buster
```
diff --git a/usr/share/hypnotix/hypnotix.ui b/usr/share/hypnotix/hypnotix.ui
index 8ec6f56..17f67f3 100644
--- a/usr/share/hypnotix/hypnotix.ui
+++ b/usr/share/hypnotix/hypnotix.ui
@@ -849,10 +849,9 @@
                             <property name="can_focus">False</property>
                             <property name="spacing">6</property>
                             <child>
-                              <object class="XAppStackSidebar">
+                              <object class="GtkStack">
                                 <property name="visible">True</property>
                                 <property name="can_focus">False</property>
-                                <property name="stack">pref_stack</property>
                               </object>
                               <packing>
                                 <property name="expand">False</property>
```

**Comment by paledega** [comment]
XAppStackSidebar required gir1.2-xapp-1.0 1.4 but debian buster has 1.2

**Comment by Arbars** [comment]
> I created a patch for debian buster
> 
> ```
> diff --git a/usr/share/hypnotix/hypnotix.ui b/usr/share/hypnotix/hypnotix.ui
> index 8ec6f56..17f67f3 100644
> --- a/usr/share/hypnotix/hypnotix.ui
> +++ b/usr/share/hypnotix/hypnotix.ui
> @@ -849,10 +849,9 @@
>                              <property name="can_focus">False</property>
>                              <property name="spacing">6</property>
>                              <child>
> -                              <object class="XAppStackSidebar">
> +                              <object class="GtkStack">
>                                  <property name="visible">True</property>
>                                  <property name="can_focus">False</property>
> -                                <property name="stack">pref_stack</property>
>                                </object>
>                                <packing>
>                                  <property name="expand">False</property>
> ```

Thansks a lot, bro! Your patch help me with build package in ALT Sisyphus! :+1: :
