### ISSUE TITLE
error in execute the program 

### ISSUE THREAD

**Issue by eduardoaddad** [linuxmint/hypnotix#87]
Error: 

```
$ Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 64, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 92, in __init__
    self.builder.add_from_file(gladefile)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/hypnotix/hypnotix.ui:846:1 Invalid object type 'XAppStackSidebar' (6)
```

**Comment by Axel-Erfurt** [comment]
Are you on Mint?

you have no xapps

**Comment by eduardoaddad** [comment]
No, use another Linux system

**Comment by eduardoaddad** [comment]
How can I install on another Linux?

**Comment by Axel-Erfurt** [comment]
https://ubuntuhandbook.org/index.php/2020/11/install-pix-xed-xplayer-xreader-xviewer-ubuntu-20-04/

**Comment by eduardoaddad** [comment]
sudo add-apt-repository ppa:savoury1/xapps

I'm not able to find this command on my Linux

**Comment by eduardoaddad** [comment]
@Axel-Erfurt how do i install ?

**Comment by Axel-Erfurt** [comment]
Maybe you can try my Lite Version of hypnotix, it does not need xapps

https://github.com/Axel-Erfurt/hypnotixLite

**Comment by eduardoaddad** [comment]
Can't download x apps per file?

**Comment by Axel-Erfurt** [comment]
try

sudo apt-get install libxapp-dev

**Comment by eduardoaddad** [comment]
sudo apt-get install libxapp-dev - done

**Comment by eduardoaddad** [comment]
the error continues even installing this

**Comment by Axel-Erfurt** [comment]
It's made for Mint

**Comment by mtwebster** [comment]
XApps 1.4 is required. It's not 'made for mint'.
