### ISSUE TITLE
When I choose BBC News, BBC News starts playing, but another channel seems selected in the panel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/hypnotix#88]
Please see [this video (on Box)](https://app.box.com/s/nytxpjavq15t5sdz1id8tr700rud88xr).

Expectation: move the highlight on the panel to show what one is watching. The problem was especially acute initially because BBC News was playing an advert for BBC 4, so I was at a loss to know what channel was playing.

(In other respects, though, Hypnotix seems great!)

**Comment by Free-IPTV** [comment]
> 
> 
> Please see [this video (on Box)](https://app.box.com/s/nytxpjavq15t5sdz1id8tr700rud88xr).
> 
> Expectation: move the highlight on the panel to show what one is watching. The problem was especially acute initially because BBC News was playing an advert for BBC 4, so I was at a loss to know what channel was playing.
> 
> (In other respects, though, Hypnotix seems great!)

 Hi LinuxOnTheDesktop,

BBC Now and BBC Four / CBeebies should be correct now. :-)

**Comment by LinuxOnTheDesktop** [comment]
@Free-IPTV 

Sorry, but what do you mean? The problem was _not_ that in the case of some channels, a channel played that was not the one that was labelled as playing. The problem was that there was insufficient labelling of which channel _is_ playing.

**Comment by Axel-Erfurt** [comment]
I think he means that the channel is not selected in hypnotix.
When you start hypnotix the top entry is marked. that doesn't change when you play a channel.

**Comment by clefebvre** [comment]
Thanks, we'll be adding favorites and more information on the channel page. This is planned.
