### ISSUE TITLE
Add support for MPV options

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/hypnotix#9]
Streams served via `rtsp://` aren't played: Nothing happens on selection (stdout mentions the channel when selected)

Example m3u file from a Fritz!Box DVB-C device:
```
#EXTM3U
#EXTINF:0,Das Erste
#EXTVLCOPT:network-caching=1000
rtsp://fritz.box:554/?avm=1&freq=120&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,15,17,20,6615
#EXTINF:0,ZDF
#EXTVLCOPT:network-caching=1000
rtsp://fritz.box:554/?avm=1&freq=128&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,15,17,20,6615,6160
#EXTINF:0,3sat
#EXTVLCOPT:network-caching=1000
rtsp://fritz.box:554/?avm=1&freq=132&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,15,17,20,6615,1632
```

**Comment by clefebvre** [comment]
Try to play it directly with mpv from the command line and see if you get any errors.

**Comment by Tibladar** [comment]
Running via mpv:
```
> mpv "rtsp://fritz.box:554/?avm=1&freq=120&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,15,17,20,6615"
[ffmpeg/demuxer] rtsp: CSeq 3 expected, 0 received.
[ffmpeg/demuxer] rtsp: method SETUP failed: 461 Unkown
[lavf] avformat_open_input() failed
Failed to recognize file format.


Exiting... (Errors when loading file)
```

A quick search revealed this issue: https://github.com/mpv-player/mpv/issues/4845
Adding the commandline options as described in https://github.com/mpv-player/mpv/issues/4845#issuecomment-428918139 worked .

**Comment by clefebvre** [comment]
I can't access your URL from here obviously. But using a publicly available stream, I can't reproduce the issue... 

`mpv "rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen02.stream"`

Support for rtsp is therefore OK, what the issue is here is that we need to be able to let the user add MPV options.

**Comment by clefebvre** [comment]
done by https://github.com/linuxmint/hypnotix/commit/87a8e61879e92203f655d838ebd38274832b4ebf
