### ISSUE TITLE
Editing channel lists and providers does not work

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/hypnotix#96]
Editing and deleting channel lists and providers does not work. For this you would have to remove **_name=_** before **_provider.name_** in **__hypnotix.py_**_ from about line 775 and 801. 

Example:
`self.navigate_to("delete_page", provider.name)`
`self.navigate_to("add_page", provider.name)`

System: Linux Mint 20.1 Cinnamon and LMDE 4

**Comment by Axel-Erfurt** [comment]
This has already been mentioned here several times. 

[#49](https://github.com/linuxmint/hypnotix/issues/49)

There is also a pull request. (unfortunately ignored)
